[package]
name = "bls-signatures-ffi"
version = "0.1.0"
authors = ["sidke <sidney@carbonfive.com>", "dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
bls-signatures = { path = ".." }
rand = "0.4"
libc = "0.2"

[build-dependencies]
cbindgen = "0.6.8"
